# Generated by Django 2.1 on 2019-01-31 12:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_detail',
            fields=[
                ('btitle', models.CharField(max_length=100)),
                ('bgenre', multiselectfield.db.fields.MultiSelectField(choices=[('fi', 'Fiction'), ('nf', 'Non-fiction'), ('cl', 'Classic'), ('ro', 'Romance'), ('fa', 'Fantasy'), ('my', 'Mystery'), ('co', 'Comics'), ('gn', 'Graphic-novel'), ('sf', 'Science-fiction'), ('hi', 'History'), ('bi', 'Biography'), ('su', 'Superhero'), ('th', 'Thriller'), ('ct', 'Contemporary'), ('ad', 'Adventure')], max_length=44)),
                ('bauthor', models.CharField(max_length=100)),
                ('bisbn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bpages', models.CharField(max_length=30)),
                ('bpublished', models.CharField(max_length=80)),
                ('bpublished_by', models.CharField(max_length=100)),
                ('bcover', models.ImageField(upload_to='book_cover')),
                ('bo_lang', models.CharField(blank=True, max_length=50)),
                ('bdesc', models.TextField(blank=True)),
            ],
        ),
    ]
